AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cors-tester

  Sample SAM Template for cors-tester
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:


######################################################################################
## REST API ##########################################################################
######################################################################################

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      # Auth:
      #   AddDefaultAuthorizerToCorsPreflight: false
      #   Authorizers:
      #     MyCognitoAuth:
      #       AuthorizationScopes:
      #         - com.cors.test/site.access
      #       UserPoolArn: !GetAtt UserPool.Arn
      #       AuthType: "COGNITO_USER_POOLS"
      #   DefaultAuthorizer: MyCognitoAuth
      StageName: Prod
      # TracingEnabled: true
      Cors:
        AllowOrigin:  "'https://obedient-duck.surge.sh'"
        AllowHeaders: "'x-my-auth-token'"
        AllowMethods: "'GET,OPTIONS'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref RestApi
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
